name: bruce
favicon: null
layout_spectrum: 0.35576
typography_spectrum: 0.17885
title: 'Sharing tidbits on Travel, Lifestyle Business and being a Digital Nomad.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4065ac'
    - '#0f0e13'
    - '#e8edf1'
    - '#474131'
    - '#c7baa7'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
