name: bruce
favicon: null
layout_spectrum: 0.7670093171764165
typography_spectrum: 0.40581094520166516
title: 'Sharing tidbits on Travel, Lifestyle Business and being a Digital Nomad.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.07514011533930898
  lightness: 0.2053592747543007
  saturation: 0.944424552610144
  rhythmicContrast: 0.3428584570065141
purpose: []
