name: bruce
favicon: null
layout_spectrum: 0.58466
typography_spectrum: 0.17885
title: 'Sharing tidbits on Travel, Lifestyle Business and being a Digital Nomad.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#3d362e'
    - '#10131c'
    - '#97a29a'
    - '#d26d8b'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
