name: bruce
favicon: null
layout_spectrum: 0.35188
typography_spectrum: 0.2836
title: 'Sharing tidbits on Travel, Lifestyle Business and being a Digital Nomad.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#659cef'
    - '#e4e0d5'
    - '#30311f'
    - '#ce1e32'
    - '#ff7c85'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
