name: bruce
favicon: null
layout_spectrum: 0.54005
typography_spectrum: 0.2836
title: 'Sharing tidbits on Travel, Lifestyle Business and being a Digital Nomad.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#535353'
    - '#c3c3c3'
    - '#fffbf8'
    - '#977547'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
